name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: dylan-lang/install-opendylan@v3
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: dylan update

      - name: Build time-test-suite
        run: dylan build time-test-suite

      - name: Run time-test-suite
        run: _build/bin/time-test-suite
