name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dylan-lang/install-opendylan@v1

      - name: list files
        run: |
          pwd
          find .

      - name: Build time-test-suite
        run: |
          pwd
          find .
          ./dylan-compiler -build -jobs 3 time-test-suite

      - name: Run time-test-suite
        run: _build/bin/time-test-suite
